name: Build clean.csv

on:
  workflow_dispatch:

permissions:
  contents:write

jobs:
  build:
    runs-on:ubuntu-latest
    steps:
      -uses: actions/checkout@v4
      -uses: actions/setup-python@v5
       with:
         python-version:"3.12"
      -run: pip install -r requirements.txt
      -name: Run script
       run:python wiki_tables.py
      -name: Commit clean.csv
       run: |
         git config user.name "github-actions"
         git config user.email "github-actions@users.noreply.github.com"
         git add clean.csv
         git commit -m "Add clean.csv" || echo "No changes"
         git push
      
      
